### ISSUE TITLE
msw option is not available in add-on panel

### ISSUE THREAD

**Issue by shrilakshmishastry** [offbeat-dev/storybook-msw-addon#1]
Not getting MSW on add on panel as shown in the example in storybook, even after passing proper params. Mocking is working fine

<img width="1153" alt="image" src="https://github.com/offbeat-dev/storybook-msw-addon/assets/29778698/44b7fb8d-d8ef-459a-b40a-ef0f6d62abad">

code for preview.js
```
initialize();
export const loaders = [mswLoader];
addParameters({
  viewport: {
    viewports: {
      ...INITIAL_VIEWPORTS,
      ...MINIMAL_VIEWPORTS,
    },
  },
});

```

code for story
```
import React from 'react';
import { rest } from 'msw';
import Dummy from './dummy';

export default {
  title: 'Dummy/fetch',
  component: Dummy,
  parameters: {
    msw: {
      handlers: [
        rest.get(
          'https://api.smallcase.com/smallcases/hello',
          (req, res, ctx) => {
            console.log('lakshmi');
            return res(
              ctx.json({
                firstName: 'Neil',
                lastName: 'Maverick',
              }),
            );
          },
        ),
      ],
    },
  },
};

const Template = () => <Dummy />;
export const fetch = Template.bind({});

```

**Comment by offbeat-dev** [comment]
hi @shrilakshmishastry.. 
have you added  **'storybook-msw-addon'** to the addons list in storybook's main.ts? 
if that doesn't work, can you share a repo or codesandbox reproducing the issue so I can take a look? thank you

**Comment by shrilakshmishastry** [comment]
Hey, thanks for the quick come back !!
Yes , I have added `storybook-msw-addon` in main.js. I can't share repo it's organisation one and private,
But I can share the version of repos I am using

 "@storybook/react": "^6.5.16"
  "@storybook/addon-actions": "^6.5.16",
  "@storybook/addon-docs": "^6.5.16",
    "@storybook/addon-essentials": "^6.5.16",
    "@storybook/addon-knobs": "^6.4.0",
    "@storybook/addon-viewport": "^6.5.16",
    "@storybook/builder-webpack5": "^6.5.16",
    "@storybook/manager-webpack5": "^6.5.16",
    "@storybook/preset-create-react-app": "^4.1.2",
    "@storybook/preview-api": "^7.3.0",
"storybook-msw-addon": "^0.3.21",
 "msw": "^1.2.3",
    "msw-storybook-addon": "^1.8.0",
    
    Is this supported for storybook react ?

**Comment by shrilakshmishastry** [comment]
is there any other dependency I should be adding along with this library?

**Comment by offbeat-dev** [comment]
hi @shrilakshmishastry I see, I think it has too do with the fact that I built the library using the addon-kit for Storybook > 7 which uses vite instead of webpack.. I haven't tested it with webpack builder.
