### ISSUE TITLE
Dependency on @storybook/icons

### ISSUE THREAD

**Issue by LiyanChen-X** [offbeat-dev/storybook-msw-addon#11]
Hi,  really like this addon and it works great. 

One issue I noticed is that I have to manually add `@storybook/icons` as a dev-dependency, otherwise the storybook will fail since you import @storybook/icons in the `manager.js` 
<img width="1598" alt="image" src="https://github.com/offbeat-dev/storybook-msw-addon/assets/43983788/de68392d-fee5-4f89-b07b-e36894fe7a34">

Any suggestions here? 

I'm working on storybook v7  and using vite as the builder. 

The failure: 
<img width="654" alt="image" src="https://github.com/offbeat-dev/storybook-msw-addon/assets/43983788/5fa69d2f-f9ea-43eb-bd4f-f1a9e873d032">

**Comment by offbeat-dev** [comment]
hi @LiyanChen-X for Storybook 7, I would recommend using **storybook-msw-addon version** version **1.3.0**

Version > 2.0.0 of the addon added support for Storybook > 8 and graphql and is not backwards compatible

I hope this helps. Let me know if you have any other questions. Thank you
