### ISSUE TITLE
v1.2.0 has no `dist` directory

### ISSUE THREAD

**Issue by lyleunderwood** [offbeat-dev/storybook-msw-addon#3]
v1.2.0, current latest on npm, has no `dist` directory and therefore can't be loaded successfully.

**Comment by lyleunderwood** [comment]
v0.3.25 from yesterday has a `dist` directory.

**Comment by offbeat-dev** [comment]
hi @lyleunderwood,

thank you for reporting. I have pushed a fix. v1.2.1 should be working as expected. please let me know. 

best,

**Comment by lyleunderwood** [comment]
works for me in v1.2.1 :+1:
