### ISSUE TITLE
Should the documentation refer to "msw-storybook-addon" instead of "storybook-msw-addon"

### ISSUE THREAD

**Issue by dalechesterfuse** [offbeat-dev/storybook-msw-addon#6]
![image](https://github.com/offbeat-dev/storybook-msw-addon/assets/114198660/d581b295-331c-45bb-819f-6cd68ded5445)

Here the intructions are referring to a different library for importing initalize, etc. 

Is this intended?

**Comment by offbeat-dev** [comment]
hi @dalechesterfuse thank you for reporting this. It is not intended. I'll fix for 2.0.4.

**Comment by offbeat-dev** [comment]
readme has been updated in 2.0.4
